version: '3.9'
services:
  postgres:
    image: postgres:15.3
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_secret
      POSTGRES_DB: postgres
    volumes:
      - /my/local/volume:/var/lib/postgresql/data
