version: '3.9'
services:
  diplomatik:
    image: fretz12/diplomatik
    restart: always
    container_name: diplomatik
    ports:
      - 8000:8000
    env_file:
      - /my/project/root/dir/.env
    network_mode: host
    command: --host 0.0.0.0
